[package]
name = "bulletformat"
version = "1.8.0"
edition = "2021"
authors = ["Jamie Whiting"]
description = "Binary Data Formats, Data Loader and Utilities for bullet."
license = "MIT"
repository = "https://github.com/jw1912/bulletformat"
readme = "README.md"
